### ISSUE TITLE
Windows VMs often have an unreliable display

### ISSUE THREAD

**Issue by jordanhendricks** [oxidecomputer/propolis#214]
When interacting with a Windows VM over VNC, sometimes the screen will go black for a second or two and return to where the screen was before. After a few iterations of this, the VM will often kick the logged in user out back to the lock screen.

The lock screen has generally been stable for a long time in my experience -- specifically, I have never seen this behavior while the VM is locked and on this screen:
![ksnip_20220922-093716](https://user-images.githubusercontent.com/6669371/191804340-b50913f7-940d-4fcc-b94b-f4623a57677b.png)

But once I'm into the password prompt screen:
![ksnip_20220922-094609](https://user-images.githubusercontent.com/6669371/191805317-22134f60-0bfa-4a9e-92cf-c6d25500f13e.png)

sometimes the screen may start to become unresponsive, with a black screen shown as such:
![ksnip_20220922-094210](https://user-images.githubusercontent.com/6669371/191805246-ddd694df-7b10-44e1-9863-226baa0302dd.png)

after enough times of this happening, I've observed the VM sometimes kicks me back to the lock screen.

**Comment by gjcolombo** [comment]
I can reproduce this with a fresh Windows Server 2022 image.

This behavior is consistent with an issue I saw in ad hoc testing some months ago. DWM got stuck in a crash loop due to QueryPerformanceCounter unexpectedly wrapping (an artifact of the choice of platform timers that Propolis and my chosen bootrom exposed to Windows). To see if this might be the same thing, I configured the system to collect crash dumps for me:

```
mkdir c:\dumps
reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps"
reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v DumpFolder /t REG_EXPAND_SZ /d "C:\dumps"
reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v DumpCount /t REG_DWORD /d 10
reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps" /v DumpType /t REG_DWORD /d 1
```

And, lo and behold, merely rebooting the system and getting to the lock screen produced a couple of DWM dumps:

```
PS C:\dumps> ls


    Directory: C:\dumps


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         9/22/2022  11:17 AM        1580858 dwm.exe.4356.dmp
-a----         9/22/2022   6:07 PM        1611708 dwm.exe.860.dmp
```

Logging in causes more of these to get created, after which I see the same behavior described above (after enough crashes I get kicked back to the lock screen).

I have a guest firmware image that I was able to use previously to resolve this problem (it sets Windows up to use the HPET for platform time and so avoids the wraparound issue). I'll try that again and see if it helps things. If it doesn't I'll start examining the dumps to see what's going on.

**Comment by gjcolombo** [comment]
Switching guest firmware images to one that allows Windows to use the emulated HPET resolves the above issue for me. I passed @jordanhendricks a copy of the bootrom I used to see if I'm just getting lucky :)

**Comment by pfmooney** [comment]
I've pushed oxidecomputer/edk2@88d5a0c744e8b7361ea55b1a552a4f63d8ebaff4 to the `propolis/edk2-stable202105` branch for now.  Where should I put the binary so that other folks don't stumble over this in the mean time?

**Comment by luqmana** [comment]
We link to https://oxide-omicron-build.s3.amazonaws.com/OVMF_CODE.fd from the README, which is also what gets pulled in for the omicron packaging stuff. I'd say just replace that and let folks know in chat too.

**Comment by gjcolombo** [comment]
> I've pushed [oxidecomputer/edk2@88d5a0c](https://github.com/oxidecomputer/edk2/commit/88d5a0c744e8b7361ea55b1a552a4f63d8ebaff4) to the `propolis/edk2-stable202105` branch for now. Where should I put the binary so that other folks don't stumble over this in the mean time?

I tested WS2022 with a bootrom built from this commit and didn't see any DWM crashes. The bootrom I used is now uploaded to https://oxide-omicron-build.s3.amazonaws.com/OVMF_CODE_20220922.fd.

I'll have a PR out shortly to update the README, package manifest, and PHD scripts.
