### ISSUE TITLE
Preserve modified page masks on migration sources

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/propolis#387]
If a migration source calls `VmmHdl::track_dirty_pages` and migration subsequently fails, the source must try to transfer the tracked pages again if it tries to migrate again, even if the guest hasn't touched those pages again.

**Comment by hawkw** [comment]
Thinking through this, here are my notes so far:

- When we call [`VmmHdl::track_dirty_pages`](https://github.com/oxidecomputer/propolis/blob/master/lib/propolis/src/vmm/hdl.rs#L237), we pass in a 4k bitmap and a start guest physical address,, and `track_dirty_pages`[^ioctl] sets a 1 in the bitmap for each page in that range that is dirty.
 - Calling `track_dirty_pages` clears the dirty bit in the virtual page table for each dirty page in the range, so it won't still look dirty after the migration request, even if it fails.
 - Right now, [we only create a single 4k bitmap](https://github.com/oxidecomputer/propolis/blob/a13ebb9a982661b1e2592a3a736b621bf2264e3d/bin/propolis-server/src/lib/migrate/source.rs#L259) and [reuse it in a loop that constructs the memory transfer requests](https://github.com/oxidecomputer/propolis/blob/a13ebb9a982661b1e2592a3a736b621bf2264e3d/bin/propolis-server/src/lib/migrate/source.rs#L278-L282)[^reuse]
 - If we want to store the dirty page information across multiple migration attempts, the naive representation of that would look sort of like a `HashMap<RangeInclusive<GuestAddr>, [u8; 4096]>`, because the page range might include more than 4096 pages.
	 - There is probably a nicer representation for this than `HashMap` but this is a sketch
	 - This means we're potentially using a lot more memory than we are right now, since the number of 4k bitmaps now scales with the size of the guest's memory, rather than only ever having one.
 - We would then need to hold onto that data structure, and if the migration attempt fails, subsequent migration attempts would bit-or their dirtiness bitmaps with a new call to `track_dirty_pages` to determine which pages need to be xferred.
	 - If a failed migration can be retried multiple times if it fails again (which I assume it can), we need to continue hanging onto the dirty-pages data, and add any pages that became dirty since the last migration attempt.
 - This naive solution seems kind of inefficient (holding onto lots of 4k bitmaps) and there are probably some annoying implementation complexities with handling ranges that start in different places, etc.
	 - Maybe there's some way to not have `bhyve` clear the dirty bits when calling `track_dirty_pages`, or we could re-dirty those pages after their dirty bits get cleared --- can we make the kernel do the work for us?


Let me know if I've gotten anything wrong in my understanding of the problem?

[^ioctl]: or, rather, the `bhyve` API we call into through an `ioctl`.
[^reuse]: if the page range has more than 4096 pages in it; otherwise, the loop only iterates once.

**Comment by pfmooney** [comment]
>  Maybe there's some way to not have `bhyve` clear the dirty bits when calling `track_dirty_pages`, or we could re-dirty those pages after their dirty bits get cleared --- can we make the kernel do the work for us?

I have a partially-finished workspace with changes which facilitate such behavior, basically making nested-page-table operations more flexible. [illumos#15639](https://www.illumos.org/issues/15639)

**Comment by hawkw** [comment]
In that case, I'm going to make my priority figuring out how to test this in PHD, and integrating with @pfmooney's upstream change when it's ready (rather than implementing the naive userspace solution).
